# Generated by Django 2.1.2 on 2018-10-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawball',
            name='ball',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='drawball',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='digits',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_digit',
            field=models.PositiveSmallIntegerField(default=58),
        ),
    ]
