# Generated by Django 2.1.2 on 2018-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181008_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pcso_game_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
