# Generated by Django 2.1.2 on 2018-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181008_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pcso_game_id',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterModelTable(
            name='drawball',
            table='draw_ball',
        ),
    ]
